# Stack Overflow Annual Developer Survey

<h3>
 We'll be using Stack Overflowover website with 70,000 responses fielded from over 180 countries, our Annual Developer Survey examines all aspects of the developer experience from learning to code to their favorite technologies to version control and the workplace experience of professional developers. as an example. You can find it here:</h3>

<a><h3>https://insights.stackoverflow.com/survey</h3></a>

<h4><b>data manipulation with groupby()</b></h4>

# Filtering :

In [2]:
# Importing libraries

import numpy as np
import pandas as pd

import os

# os.getcwd()

In [3]:
# Loading dataset

fileName = 'survey_results_public.csv'
schemaName = 'survey_results_schema.csv'


df = pd.read_csv(fileName, index_col='ResponseId') 
schema_df = pd.read_csv(schemaName,index_col='qname')

In [5]:
# Filter a counties with high salarirs

high_salary = (df['ConvertedCompYearly'] > 70000)

In [6]:
df.loc[high_salary,['Country','LanguageHaveWorkedWith','ConvertedCompYearly']]

,Country,LanguageHaveWorkedWith,ConvertedCompYearly
ResponseId,,,
13,Germany,C;C++;Java;Perl;Ruby,77290.0
19,Singapore,C++;Python,160932.0
25,Germany,C++;HTML/CSS;Java;JavaScript;Kotlin;Node.js;Ty...,77831.0
27,Switzerland,C++;Python,81319.0
32,Israel,Bash/Shell;Go;Java;Node.js;Python;Scala;SQL,122580.0
...,...,...,...
83431,United States of America,APL;Clojure;LISP;Python;Ruby;SQL;TypeScript,125000.0
83433,Canada,Ruby,80169.0
83435,United States of America,Clojure;Kotlin;SQL,160500.0
83437,United States of America,Groovy;Java;Python,90000.0
83438,Canada,Bash/Shell;JavaScript;Node.js;Python,816816.0

In [7]:
# Filtering by specific country

countries = ['United States of America','Sweden','Russian Federation']

filt1 = df['Country'].isin(countries)
df.loc[filt1]

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
6,I am a student who is learning to code,"Student, part-time",United States of America,Georgia,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Prefer not to say,No,Straight / Heterosexual,Prefer not to say,None of the above,I have a concentration and/or memory disorder ...,Too long,Neither easy nor difficult,NaN
7,I code primarily as a hobby,I prefer not to say,United States of America,New Hampshire,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",3,NaN,...,Prefer not to say,Prefer not to say,No,NaN,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
10,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,7,4,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,51552.0
16,I am a student who is learning to code,"Student, full-time",United States of America,Missouri,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Other (please specify):,7,NaN,...,Under 18 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Too long,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83428,I am a developer by profession,Employed full-time,United States of America,Pennsylvania,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",13,2,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,"I have an anxiety disorder;Or, in your own words:",Too short,Easy,4300000.0
83430,I code primarily as a hobby,"Not employed, but looking for work",United States of America,Washington,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",6,NaN,...,25-34 years old,"Man;Or, in your own words:",Yes,Queer,White or of European descent,I am unable to / find it difficult to walk or ...,I have an anxiety disorder,Appropriate in length,Neither easy nor difficult,NaN
83431,I am a developer by profession,Employed full-time,United States of America,Illinois,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",23,21,...,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,125000.0
83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0

In [8]:
df.head()

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelorâ€™s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Masterâ€™s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [11]:
import seaborn as sns